# Generated by Django 5.2.12 on 2026-03-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuserprofile',
            name='session_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authuserprofile',
            name='session_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
