# Generated by Django 5.1.2 on 2026-04-01 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuserprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
        migrations.AlterModelTable(
            name='authuserprofile',
            table='auth_user_profile',
        ),
        migrations.AlterModelTable(
            name='contactmessage',
            table='contact_message',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='meeting',
            table='meeting',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='team_member',
        ),
    ]
