# Generated by Django 5.2.12 on 2026-04-03 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_authuserprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_conversation', models.TextField()),
                ('receiver_conversation', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(db_column='recipient_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_direct_messages', to='accounts.authuserprofile', to_field='user')),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_direct_messages', to='accounts.authuserprofile', to_field='user')),
            ],
            options={
                'db_table': 'message_conversation',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
