# Generated by Django 5.2.12 on 2026-04-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatmessage_ordering'),
    ]

    operations = [
        # First, drop the incorrect foreign key constraint
        migrations.RunSQL(
            sql="ALTER TABLE chat_message DROP CONSTRAINT IF EXISTS chat_message_session_id_9abc6edf_fk_chat_session_id;",
            reverse_sql="ALTER TABLE chat_message ADD CONSTRAINT chat_message_session_id_9abc6edf_fk_chat_session_id FOREIGN KEY (session_id) REFERENCES chat_session(id);",
        ),
        # Then, change the column type from bigint to varchar
        migrations.RunSQL(
            sql="ALTER TABLE chat_message ALTER COLUMN session_id TYPE character varying(255);",
            reverse_sql="ALTER TABLE chat_message ALTER COLUMN session_id TYPE bigint;",
        ),
    ]
