# Generated by Django 5.2.12 on 2026-04-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_fix_session_id_type'),
    ]

    operations = [
        # Remove unused columns from chat_session
        migrations.RunSQL(
            sql="""
            ALTER TABLE chat_session DROP COLUMN IF EXISTS current_agent;
            ALTER TABLE chat_session DROP COLUMN IF EXISTS is_active;
            ALTER TABLE chat_session DROP COLUMN IF EXISTS last_activity_at;
            ALTER TABLE chat_session DROP COLUMN IF EXISTS meeting_state;
            """,
            reverse_sql="""
            ALTER TABLE chat_session ADD COLUMN current_agent varchar(20);
            ALTER TABLE chat_session ADD COLUMN is_active boolean;
            ALTER TABLE chat_session ADD COLUMN last_activity_at timestamp with time zone;
            ALTER TABLE chat_session ADD COLUMN meeting_state jsonb;
            """,
        ),
        # Remove unused columns from chat_message
        migrations.RunSQL(
            sql="""
            ALTER TABLE chat_message DROP COLUMN IF EXISTS agent_type;
            """,
            reverse_sql="""
            ALTER TABLE chat_message ADD COLUMN agent_type varchar(20);
            """,
        ),
    ]
