# Generated by Django 5.2.12 on 2026-04-02 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_unused_chat_session_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('is_meeting_request', models.BooleanField(default=False)),
                ('meeting_title', models.CharField(blank=True, max_length=255)),
                ('meeting_time', models.CharField(blank=True, max_length=255)),
                ('agenda', models.TextField(blank=True)),
                ('participants_json', models.TextField(default='[]')),
                ('missing_details_json', models.TextField(default='[]')),
                ('status', models.CharField(choices=[('collecting', 'Collecting information'), ('validating', 'Validating details'), ('scheduling', 'Scheduling meeting'), ('completed', 'Meeting scheduled'), ('failed', 'Failed')], default='collecting', max_length=50)),
                ('last_turn_summary', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('meeting_id', models.IntegerField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_state',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'session_id')},
            },
        ),
    ]
