# Generated by Django 5.2.12 on 2026-04-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_agentstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentstate',
            name='status',
            field=models.CharField(choices=[('collecting', 'Collecting information'), ('in_progress', 'In progress'), ('confirming', 'Awaiting user confirmation'), ('completed', 'Meeting scheduled'), ('failed', 'Failed')], default='collecting', max_length=50),
        ),
    ]
