export interface ProjectTeamMember {
  memberId: string;
  role: string;
}

export interface ProjectFile {
  title: string;
  type: string;
  updatedAt: string;
}

export interface ProjectExampleTask {
  title: string;
  description: string;
  assigneeRole: string;
  priority: "low" | "medium" | "high";
  status: "todo" | "inprogress" | "completed";
  dueLabel: string;
}

export interface ProjectRecord {
  id: string;
  name: string;
  description: string;
  objective: string;
  summary: string;
  users: string;
  scope: string[];
  firstSteps: string[];
  exampleTasks: ProjectExampleTask[];
  expectedOutput: string;
  startDate: string;
  deadline: string;
  status: "Planning" | "Active" | "At Risk" | "Completed";
  ownerId: string;
  progress: number;
  team: ProjectTeamMember[];
  files: ProjectFile[];
}

export const PROJECTS: ProjectRecord[] = [
  {
    id: "72ipo",
    name: "72ipo",
    description: "A website where users can view IPO information, updates, and related landing pages.",
    objective: "Help the team publish IPO details quickly and help users understand those details clearly.",
    summary: "72ipo is a project used to show IPO-related information in one place. It helps the internal team manage content like IPO pages, updates, and campaign sections, and it helps users read that information easily. If you work on this project, you may update page content, improve layouts, connect API data, or fix issues in the dashboard and landing pages.",
    users: "Used by internal content/marketing teams to publish IPO updates and by external visitors to read IPO information and offers.",
    scope: ["IPO landing pages", "Investor updates", "Content publishing", "Dashboard widgets", "Campaign pages"],
    firstSteps: [
      "Open the project tasks and identify the ticket assigned to you.",
      "Review the design and API documentation before changing UI or content logic.",
      "Confirm page owner or reviewer before moving work to completed.",
    ],
    exampleTasks: [
      {
        title: "Update IPO landing page hero",
        description: "Refresh campaign headline, CTA, and offer copy for the latest IPO release.",
        assigneeRole: "Frontend Developer",
        priority: "high",
        status: "inprogress",
        dueLabel: "Apr 4, 2026",
      },
      {
        title: "Fix mobile layout in investor updates",
        description: "Resolve spacing and overflow issues on card sections for small screens.",
        assigneeRole: "Frontend Developer",
        priority: "medium",
        status: "todo",
        dueLabel: "Apr 7, 2026",
      },
      {
        title: "Connect new API fields to dashboard cards",
        description: "Map latest backend response fields into summary widgets and validate data states.",
        assigneeRole: "Backend Developer",
        priority: "high",
        status: "completed",
        dueLabel: "Mar 28, 2026",
      },
    ],
    expectedOutput: "Your work should keep the IPO content accurate, easy to publish, and visually consistent across landing pages and dashboards.",
    startDate: "2025-07-10",
    deadline: "2026-04-15",
    status: "Active",
    ownerId: "1",
    progress: 68,
    team: [
      { memberId: "1", role: "Project Manager" },
      { memberId: "2", role: "Frontend Developer" },
      { memberId: "3", role: "Backend Developer" },
      { memberId: "4", role: "Designer" },
    ],
    files: [
      { title: "Project Requirements", type: "PDF", updatedAt: "2026-02-18" },
      { title: "Design Files", type: "Figma", updatedAt: "2026-03-01" },
      { title: "API Documentation", type: "Docs", updatedAt: "2026-03-05" },
    ],
  },
  {
    id: "monashee-insights",
    name: "Monashee Insights",
    description: "Insight and analytics portal for dashboards, reports, and executive views.",
    objective: "Give leadership and operations teams reliable decision-making dashboards with consistent reporting.",
    summary: "Monashee Insights helps stakeholders understand business performance quickly. The team is focused on accurate metrics, faster reporting, and a dashboard experience that reduces manual effort.",
    users: "Used by management and operations teams to read KPI dashboards, reports, and performance summaries.",
    scope: ["KPI dashboards", "Filters", "Charts", "Report views", "Data summaries"],
    firstSteps: [
      "Read KPI definitions before touching charts or report labels.",
      "Verify the API/data contract if a number looks incorrect.",
      "Check with the owner before updating executive-facing metrics.",
    ],
    exampleTasks: [
      {
        title: "Add KPI card to leadership dashboard",
        description: "Introduce a new monthly performance card with tooltip and drill-down link.",
        assigneeRole: "Frontend Developer",
        priority: "high",
        status: "inprogress",
        dueLabel: "Apr 8, 2026",
      },
      {
        title: "Improve chart filter behavior",
        description: "Make date range filters sync correctly across charts and summary tables.",
        assigneeRole: "Data Engineer",
        priority: "medium",
        status: "todo",
        dueLabel: "Apr 10, 2026",
      },
      {
        title: "Fix report table mismatch",
        description: "Resolve inconsistent values between the exported report and on-screen chart totals.",
        assigneeRole: "Project Manager",
        priority: "high",
        status: "completed",
        dueLabel: "Mar 30, 2026",
      },
    ],
    expectedOutput: "Changes must keep metrics accurate, readable, and consistent across all reporting screens.",
    startDate: "2025-09-01",
    deadline: "2026-05-20",
    status: "Active",
    ownerId: "2",
    progress: 54,
    team: [
      { memberId: "2", role: "Project Manager" },
      { memberId: "3", role: "Data Engineer" },
      { memberId: "5", role: "Frontend Developer" },
    ],
    files: [
      { title: "Requirements Matrix", type: "Sheet", updatedAt: "2026-02-11" },
      { title: "Dashboard Wireframes", type: "Figma", updatedAt: "2026-02-25" },
      { title: "KPI Definitions", type: "Docs", updatedAt: "2026-03-03" },
    ],
  },
  {
    id: "real-estate",
    name: "Real Estate",
    description: "Lead capture and property showcase platform for listings, forms, and campaign pages.",
    objective: "Increase quality lead generation while keeping listing updates and campaign publishing easy for the internal team.",
    summary: "The Real Estate project supports listing visibility, lead capture, and campaign execution. The team is trying to keep the experience conversion-friendly while making operations easier for content and sales teams.",
    users: "Used by visitors exploring properties and by internal teams managing listings, campaigns, and lead flow.",
    scope: ["Property listings", "Lead forms", "Campaign pages", "CRM sync", "Content updates"],
    firstSteps: [
      "Understand the lead form flow and where inquiries are stored.",
      "Review property card/listing structure before editing templates.",
      "Validate content changes with the project owner before publish.",
    ],
    exampleTasks: [
      {
        title: "Add featured properties section",
        description: "Create a homepage section highlighting selected listings with strong CTA placement.",
        assigneeRole: "Frontend Developer",
        priority: "medium",
        status: "inprogress",
        dueLabel: "Apr 6, 2026",
      },
      {
        title: "Fix inquiry form validation",
        description: "Correct validation rules and error messaging in the lead capture flow.",
        assigneeRole: "CRM Integrations",
        priority: "high",
        status: "todo",
        dueLabel: "Apr 5, 2026",
      },
      {
        title: "Improve property details layout",
        description: "Rework media and contact sections to improve lead conversion on listing pages.",
        assigneeRole: "Project Manager",
        priority: "medium",
        status: "completed",
        dueLabel: "Mar 27, 2026",
      },
    ],
    expectedOutput: "Your work should improve lead capture, keep listing pages stable, and avoid breaking the content workflow for operations.",
    startDate: "2025-08-14",
    deadline: "2026-06-10",
    status: "Active",
    ownerId: "4",
    progress: 47,
    team: [
      { memberId: "4", role: "Project Manager" },
      { memberId: "1", role: "Frontend Developer" },
      { memberId: "5", role: "CRM Integrations" },
    ],
    files: [
      { title: "Lead Flow Document", type: "PDF", updatedAt: "2026-02-09" },
      { title: "Campaign Design Kit", type: "Figma", updatedAt: "2026-02-20" },
      { title: "CRM Mapping", type: "Docs", updatedAt: "2026-03-04" },
    ],
  },
  {
    id: "pulse-hq",
    name: "Pulse HQ",
    description: "Internal operations workspace for approvals, team updates, and workflow visibility.",
    objective: "Reduce manual follow-ups by giving teams one place to manage approvals, updates, and operational tasks.",
    summary: "Pulse HQ supports internal operations across departments. The work includes approval flows, operational dashboards, and workspace improvements that help teams move requests faster and with fewer manual check-ins.",
    users: "Used by operations, finance, HR, and leadership teams to track requests, updates, and approvals.",
    scope: ["Approval workflows", "Operations dashboard", "Activity feeds", "Notifications", "Team reporting"],
    firstSteps: [
      "Review the active workflow that your task belongs to before making UI or logic changes.",
      "Check approval states and user roles before editing forms or status transitions.",
      "Confirm with the owner which teams are affected by the change before shipping.",
    ],
    exampleTasks: [
      {
        title: "Build approvals overview widget",
        description: "Add a dashboard widget showing pending approvals by team and urgency.",
        assigneeRole: "Frontend Developer",
        priority: "high",
        status: "inprogress",
        dueLabel: "Apr 9, 2026",
      },
      {
        title: "Add escalation state to requests",
        description: "Support escalation flags and display logic in the workflow timeline.",
        assigneeRole: "Backend Developer",
        priority: "medium",
        status: "todo",
        dueLabel: "Apr 11, 2026",
      },
      {
        title: "Refine approvals empty states",
        description: "Improve guidance copy and CTA behavior when no approvals are pending.",
        assigneeRole: "Designer",
        priority: "low",
        status: "completed",
        dueLabel: "Mar 29, 2026",
      },
    ],
    expectedOutput: "Changes should make internal workflows easier to follow, reduce approval delays, and keep team visibility high.",
    startDate: "2025-10-03",
    deadline: "2026-05-28",
    status: "Active",
    ownerId: "5",
    progress: 39,
    team: [
      { memberId: "5", role: "Project Manager" },
      { memberId: "1", role: "Frontend Developer" },
      { memberId: "3", role: "Backend Developer" },
      { memberId: "4", role: "Designer" },
    ],
    files: [
      { title: "Workflow Map", type: "Docs", updatedAt: "2026-02-14" },
      { title: "Ops Dashboard Wireframes", type: "Figma", updatedAt: "2026-02-27" },
      { title: "Permissions Matrix", type: "Sheet", updatedAt: "2026-03-06" },
    ],
  },
  {
    id: "lumen-support",
    name: "Lumen Support",
    description: "Customer support portal for ticket triage, response templates, and help content.",
    objective: "Help support teams respond faster by improving ticket workflows, self-service content, and queue visibility.",
    summary: "Lumen Support focuses on triage speed, clearer response workflows, and easier access to support knowledge. The project includes queue management, ticket details, macros, and knowledge base improvements.",
    users: "Used by support agents, team leads, and customers accessing help content.",
    scope: ["Ticket queues", "Knowledge base", "Response templates", "Agent dashboards", "SLA alerts"],
    firstSteps: [
      "Review the ticket lifecycle and SLA rules before changing queue behavior.",
      "Check support copy and macros before updating user-facing text.",
      "Validate agent workflows in both desktop and mobile layouts.",
    ],
    exampleTasks: [
      {
        title: "Create SLA alert badges",
        description: "Surface overdue and at-risk ticket states clearly in the queue list.",
        assigneeRole: "Frontend Developer",
        priority: "high",
        status: "todo",
        dueLabel: "Apr 12, 2026",
      },
      {
        title: "Add macro usage analytics",
        description: "Track template usage and response performance for team leads.",
        assigneeRole: "Data Engineer",
        priority: "medium",
        status: "inprogress",
        dueLabel: "Apr 14, 2026",
      },
      {
        title: "Refresh help article layout",
        description: "Improve content readability and related-article discovery in the knowledge base.",
        assigneeRole: "Designer",
        priority: "medium",
        status: "completed",
        dueLabel: "Mar 31, 2026",
      },
    ],
    expectedOutput: "The support experience should become faster for agents and clearer for customers looking for answers.",
    startDate: "2025-11-18",
    deadline: "2026-06-18",
    status: "Planning",
    ownerId: "3",
    progress: 24,
    team: [
      { memberId: "3", role: "Project Manager" },
      { memberId: "2", role: "Frontend Developer" },
      { memberId: "4", role: "Designer" },
      { memberId: "5", role: "Data Engineer" },
    ],
    files: [
      { title: "Support Flow Audit", type: "PDF", updatedAt: "2026-02-10" },
      { title: "Queue Redesign", type: "Figma", updatedAt: "2026-02-26" },
      { title: "SLA Rules", type: "Docs", updatedAt: "2026-03-07" },
    ],
  },
  {
    id: "crm-website-design",
    name: "CRM Website Design",
    description: "Marketing site refresh for product pages, conversion journeys, and feature storytelling.",
    objective: "Improve product discovery and lead conversion through a sharper website structure and cleaner content flow.",
    summary: "CRM Website Design is focused on the public-facing product site. Work includes page hierarchy, content blocks, interactive sections, and forms that help visitors understand the platform and request demos faster.",
    users: "Used by prospects, marketing teams, and sales teams who depend on stronger conversion pages.",
    scope: ["Landing pages", "Product pages", "Conversion forms", "Feature sections", "Pricing narratives"],
    firstSteps: [
      "Review the current conversion funnel before changing page layout.",
      "Check approved copy before editing headings or CTA sections.",
      "Confirm responsive behavior for all new sections before handoff.",
    ],
    exampleTasks: [
      {
        title: "Restructure product comparison section",
        description: "Improve readability of plan comparison blocks and support stronger CTA placement.",
        assigneeRole: "Frontend Developer",
        priority: "high",
        status: "inprogress",
        dueLabel: "Apr 13, 2026",
      },
      {
        title: "Refresh demo request flow",
        description: "Simplify the form layout and reduce friction in the final submission step.",
        assigneeRole: "Designer",
        priority: "medium",
        status: "todo",
        dueLabel: "Apr 16, 2026",
      },
      {
        title: "Publish revised pricing page copy",
        description: "Apply approved messaging updates for plan descriptions and FAQs.",
        assigneeRole: "Project Manager",
        priority: "low",
        status: "completed",
        dueLabel: "Apr 1, 2026",
      },
    ],
    expectedOutput: "The website should feel clearer, convert better, and stay easy for marketing teams to update.",
    startDate: "2025-12-02",
    deadline: "2026-06-25",
    status: "Active",
    ownerId: "4",
    progress: 42,
    team: [
      { memberId: "4", role: "Project Manager" },
      { memberId: "1", role: "Frontend Developer" },
      { memberId: "2", role: "Designer" },
      { memberId: "5", role: "Content Reviewer" },
    ],
    files: [
      { title: "Site Map", type: "Docs", updatedAt: "2026-02-22" },
      { title: "Marketing Wireframes", type: "Figma", updatedAt: "2026-03-01" },
      { title: "Copy Deck", type: "Docs", updatedAt: "2026-03-08" },
    ],
  },
  {
    id: "atlas-finops",
    name: "Atlas FinOps",
    description: "Finance operations dashboard for reconciliation, payout tracking, and audit visibility.",
    objective: "Reduce manual finance follow-up by centralizing payout and reconciliation workflows.",
    summary: "Atlas FinOps helps finance teams monitor reconciliations, payout issues, and approval gaps in one place. The team is working on visibility, exception handling, and reducing spreadsheet-heavy processes.",
    users: "Used by finance analysts, approvers, and operations leads managing payouts and reconciliation issues.",
    scope: ["Reconciliation dashboards", "Payout tracking", "Exceptions", "Audit logs", "Approval history"],
    firstSteps: [
      "Review payout lifecycle and exception states before changing logic.",
      "Validate any finance metric labels against audit definitions.",
      "Check with finance owner before changing approval wording or thresholds.",
    ],
    exampleTasks: [
      {
        title: "Add payout exceptions panel",
        description: "Highlight failed or delayed payouts in a visible dashboard section.",
        assigneeRole: "Frontend Developer",
        priority: "high",
        status: "todo",
        dueLabel: "Apr 15, 2026",
      },
      {
        title: "Improve reconciliation export format",
        description: "Align exported columns with the finance team review template.",
        assigneeRole: "Backend Developer",
        priority: "medium",
        status: "inprogress",
        dueLabel: "Apr 17, 2026",
      },
      {
        title: "Document audit trail filters",
        description: "Clarify filter usage for audit review workflows.",
        assigneeRole: "Project Manager",
        priority: "low",
        status: "completed",
        dueLabel: "Apr 2, 2026",
      },
    ],
    expectedOutput: "Finance teams should be able to spot issues faster and review payout state without manual reconciliation work.",
    startDate: "2025-11-05",
    deadline: "2026-07-02",
    status: "Active",
    ownerId: "1",
    progress: 36,
    team: [
      { memberId: "1", role: "Project Manager" },
      { memberId: "3", role: "Backend Developer" },
      { memberId: "5", role: "Frontend Developer" },
    ],
    files: [
      { title: "Finance Workflow Notes", type: "Docs", updatedAt: "2026-02-17" },
      { title: "Exception States", type: "Sheet", updatedAt: "2026-02-28" },
      { title: "Audit Dashboard Mockups", type: "Figma", updatedAt: "2026-03-06" },
    ],
  },
  {
    id: "northstar-hiring",
    name: "Northstar Hiring",
    description: "Recruitment operations portal for candidate pipelines, interview loops, and hiring visibility.",
    objective: "Make hiring pipelines easier to manage while giving recruiters and managers shared visibility.",
    summary: "Northstar Hiring supports recruiting workflows from candidate intake to interview feedback. The focus is on pipeline clarity, scheduling handoffs, and reducing friction between recruiters and hiring managers.",
    users: "Used by recruiters, coordinators, interviewers, and hiring managers.",
    scope: ["Candidate pipeline", "Interview scheduling", "Feedback forms", "Hiring dashboards", "Status notifications"],
    firstSteps: [
      "Review the candidate stage flow before editing labels or transitions.",
      "Check interviewer permissions before changing feedback behavior.",
      "Validate all notification copy with recruiting ops before release.",
    ],
    exampleTasks: [
      {
        title: "Create interviewer load view",
        description: "Show scheduled interviews by interviewer to avoid overbooking.",
        assigneeRole: "Frontend Developer",
        priority: "medium",
        status: "inprogress",
        dueLabel: "Apr 18, 2026",
      },
      {
        title: "Add feedback reminder triggers",
        description: "Send reminders when interview feedback is missing past SLA.",
        assigneeRole: "Backend Developer",
        priority: "high",
        status: "todo",
        dueLabel: "Apr 20, 2026",
      },
      {
        title: "Polish candidate profile header",
        description: "Improve clarity of stage, owner, and interview summary at the top of profiles.",
        assigneeRole: "Designer",
        priority: "low",
        status: "completed",
        dueLabel: "Apr 3, 2026",
      },
    ],
    expectedOutput: "The hiring workflow should feel organized, visible, and easier to manage at each stage.",
    startDate: "2026-01-09",
    deadline: "2026-07-15",
    status: "Planning",
    ownerId: "2",
    progress: 22,
    team: [
      { memberId: "2", role: "Project Manager" },
      { memberId: "3", role: "Backend Developer" },
      { memberId: "4", role: "Designer" },
      { memberId: "5", role: "Frontend Developer" },
    ],
    files: [
      { title: "Hiring Ops Notes", type: "Docs", updatedAt: "2026-02-19" },
      { title: "Candidate Journey Map", type: "Figma", updatedAt: "2026-03-02" },
      { title: "Notification Rules", type: "Docs", updatedAt: "2026-03-09" },
    ],
  },
  {
    id: "greenleaf-academy",
    name: "Greenleaf Academy",
    description: "Learning portal for course modules, student progress, and assessment workflows.",
    objective: "Help learners complete courses smoothly while giving admins a clear view of progress and content health.",
    summary: "Greenleaf Academy is a training platform project centered on courses, progress tracking, and assessment management. The team is improving clarity for learners and reducing admin effort around content publishing and reporting.",
    users: "Used by learners, instructors, and training administrators.",
    scope: ["Course modules", "Progress tracking", "Assessments", "Admin reporting", "Content publishing"],
    firstSteps: [
      "Understand the learner journey before editing module flow.",
      "Review assessment rules before changing grading or submission states.",
      "Check content ownership before updating published course copy.",
    ],
    exampleTasks: [
      {
        title: "Improve module completion banners",
        description: "Add clearer next-step prompts after learners finish a module.",
        assigneeRole: "Designer",
        priority: "medium",
        status: "todo",
        dueLabel: "Apr 21, 2026",
      },
      {
        title: "Build assessment summary cards",
        description: "Show attempt count, score, and pending reviews in the admin view.",
        assigneeRole: "Frontend Developer",
        priority: "high",
        status: "inprogress",
        dueLabel: "Apr 19, 2026",
      },
      {
        title: "Finalize course archive rules",
        description: "Document and apply archive conditions for outdated content.",
        assigneeRole: "Project Manager",
        priority: "low",
        status: "completed",
        dueLabel: "Apr 1, 2026",
      },
    ],
    expectedOutput: "Course progress should feel clearer for learners and easier to monitor for admins.",
    startDate: "2025-12-15",
    deadline: "2026-07-08",
    status: "Active",
    ownerId: "5",
    progress: 51,
    team: [
      { memberId: "5", role: "Project Manager" },
      { memberId: "1", role: "Frontend Developer" },
      { memberId: "4", role: "Designer" },
    ],
    files: [
      { title: "Course Content Matrix", type: "Sheet", updatedAt: "2026-02-23" },
      { title: "Learner Flow Designs", type: "Figma", updatedAt: "2026-03-04" },
      { title: "Assessment Rules", type: "Docs", updatedAt: "2026-03-10" },
    ],
  },
  {
    id: "supply-sync",
    name: "Supply Sync",
    description: "Operations platform for inventory visibility, fulfillment updates, and warehouse coordination.",
    objective: "Improve inventory and fulfillment visibility so operations teams can respond faster to delays and stock gaps.",
    summary: "Supply Sync supports inventory tracking, fulfillment monitoring, and warehouse communication. The project focuses on operational clarity, status accuracy, and fewer manual escalations across teams.",
    users: "Used by warehouse teams, operations managers, and support leads handling fulfillment issues.",
    scope: ["Inventory status", "Fulfillment tracking", "Warehouse updates", "Delay alerts", "Operational dashboards"],
    firstSteps: [
      "Check the inventory status model before adjusting task logic.",
      "Review warehouse update flows before changing notification timing.",
      "Validate any status terminology with operations before release.",
    ],
    exampleTasks: [
      {
        title: "Add delayed shipment queue",
        description: "Group delayed fulfillment items into a dedicated action view.",
        assigneeRole: "Frontend Developer",
        priority: "high",
        status: "todo",
        dueLabel: "Apr 22, 2026",
      },
      {
        title: "Map stockout escalation flow",
        description: "Define notification and owner rules for stockout scenarios.",
        assigneeRole: "Project Manager",
        priority: "medium",
        status: "inprogress",
        dueLabel: "Apr 23, 2026",
      },
      {
        title: "Clean up fulfillment status legend",
        description: "Make warehouse and support terminology more consistent.",
        assigneeRole: "Designer",
        priority: "low",
        status: "completed",
        dueLabel: "Apr 5, 2026",
      },
    ],
    expectedOutput: "Ops teams should be able to understand inventory and fulfillment risk more quickly from the workspace.",
    startDate: "2026-01-20",
    deadline: "2026-07-20",
    status: "At Risk",
    ownerId: "3",
    progress: 29,
    team: [
      { memberId: "3", role: "Project Manager" },
      { memberId: "1", role: "Frontend Developer" },
      { memberId: "4", role: "Designer" },
      { memberId: "5", role: "Operations Analyst" },
    ],
    files: [
      { title: "Inventory Status Rules", type: "Docs", updatedAt: "2026-02-24" },
      { title: "Fulfillment Board", type: "Figma", updatedAt: "2026-03-05" },
      { title: "Escalation Matrix", type: "Sheet", updatedAt: "2026-03-11" },
    ],
  },
  {
    id: "orbit-suite",
    name: "Orbit Suite",
    description: "Executive workspace for goals, company updates, and strategic initiative tracking.",
    objective: "Give leadership a cleaner view of strategic work and make status reporting easier across teams.",
    summary: "Orbit Suite is a leadership-facing workspace that organizes strategic initiatives, updates, milestones, and ownership. The project is focused on clarity, progress reporting, and reducing fragmented status communication across departments.",
    users: "Used by leadership, strategy teams, and department heads reviewing company initiatives.",
    scope: ["Initiative dashboards", "Milestone tracking", "Leadership updates", "Status summaries", "Ownership views"],
    firstSteps: [
      "Review the initiative hierarchy before changing labels or grouping.",
      "Confirm milestone definitions with the owner before updating progress visuals.",
      "Validate any executive-facing copy before publishing updates.",
    ],
    exampleTasks: [
      {
        title: "Create strategic milestones panel",
        description: "Show major initiative milestones with owner and status in one summary section.",
        assigneeRole: "Frontend Developer",
        priority: "high",
        status: "inprogress",
        dueLabel: "Apr 24, 2026",
      },
      {
        title: "Add leadership digest filters",
        description: "Allow updates to be filtered by team, priority, and time range.",
        assigneeRole: "Backend Developer",
        priority: "medium",
        status: "todo",
        dueLabel: "Apr 26, 2026",
      },
      {
        title: "Polish initiative status badges",
        description: "Improve hierarchy and readability of status badges in update cards.",
        assigneeRole: "Designer",
        priority: "low",
        status: "completed",
        dueLabel: "Apr 7, 2026",
      },
    ],
    expectedOutput: "Leaders should be able to understand strategic progress quickly without digging through scattered updates.",
    startDate: "2026-02-03",
    deadline: "2026-07-29",
    status: "Active",
    ownerId: "1",
    progress: 33,
    team: [
      { memberId: "1", role: "Project Manager" },
      { memberId: "2", role: "Backend Developer" },
      { memberId: "4", role: "Designer" },
      { memberId: "5", role: "Frontend Developer" },
    ],
    files: [
      { title: "Initiative Tracker", type: "Sheet", updatedAt: "2026-03-01" },
      { title: "Leadership Dashboard", type: "Figma", updatedAt: "2026-03-07" },
      { title: "Status Reporting Guide", type: "Docs", updatedAt: "2026-03-12" },
    ],
  },
  {
    id: "harbor-pay",
    name: "Harbor Pay",
    description: "Payments workspace for merchant onboarding, settlements, and transaction visibility.",
    objective: "Improve merchant operations by making payment status, onboarding, and settlement issues easier to manage.",
    summary: "Harbor Pay supports payment operations teams working on merchant setup, settlements, transaction issues, and reporting. The project aims to reduce manual investigation and give teams a clearer operational view of payment health.",
    users: "Used by payment operations, merchant success teams, and finance stakeholders.",
    scope: ["Merchant onboarding", "Settlement tracking", "Transaction issues", "Ops reporting", "Alert workflows"],
    firstSteps: [
      "Review the merchant onboarding flow before changing forms or statuses.",
      "Check settlement states and issue types before updating queue logic.",
      "Validate alert and payment terminology with operations before release.",
    ],
    exampleTasks: [
      {
        title: "Build merchant onboarding checklist",
        description: "Create a guided setup checklist with document and KYC checkpoints.",
        assigneeRole: "Frontend Developer",
        priority: "high",
        status: "todo",
        dueLabel: "Apr 25, 2026",
      },
      {
        title: "Add settlement issue summary",
        description: "Highlight stuck settlements and unresolved issues in the operations overview.",
        assigneeRole: "Project Manager",
        priority: "medium",
        status: "inprogress",
        dueLabel: "Apr 27, 2026",
      },
      {
        title: "Refresh payment alert copy",
        description: "Improve clarity of operational alert messaging for payment failures.",
        assigneeRole: "Designer",
        priority: "low",
        status: "completed",
        dueLabel: "Apr 8, 2026",
      },
    ],
    expectedOutput: "Payment operations should become easier to monitor, with fewer manual handoffs and clearer issue visibility.",
    startDate: "2026-02-10",
    deadline: "2026-08-04",
    status: "Planning",
    ownerId: "3",
    progress: 18,
    team: [
      { memberId: "3", role: "Project Manager" },
      { memberId: "1", role: "Frontend Developer" },
      { memberId: "4", role: "Designer" },
      { memberId: "5", role: "Operations Analyst" },
    ],
    files: [
      { title: "Merchant Flow Audit", type: "Docs", updatedAt: "2026-03-03" },
      { title: "Settlement Queue Mockups", type: "Figma", updatedAt: "2026-03-09" },
      { title: "Alert Definitions", type: "Docs", updatedAt: "2026-03-12" },
    ],
  },
];

export function getProjectById(projectId?: string) {
  return PROJECTS.find((project) => project.id === projectId);
}
